### ISSUE TITLE
Search fails when launched in EU-West-1

### ISSUE THREAD

**Issue by msbishop** [awslabs/serverless-photo-recognition#11]
Great tool, thanks! 

Search fails (Sample command) because the Cognito pool apparently can't be found. 

According to this: http://stackoverflow.com/questions/27137299/amazon-cognito-connection-cannot-find-identitypool may be a region issue. 

Detailed trace: 
`IdentityPool 'eu-west-1:9759c8b7-2f08-4689-be3f-0fcb416aa091' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 06e74c12-0f3e-11e7-b97a-697f028f5f61): com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException
com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'eu-west-1:9759c8b7-2f08-4689-be3f-0fcb416aa091' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 06e74c12-0f3e-11e7-b97a-697f028f5f61)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.doInvoke(AmazonCognitoIdentityClient.java:1385)
at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1361)
at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:679)
at com.budilov.SearchPhotosHandler.getCognitoId(SearchPhotosHandler.kt:86)
at com.budilov.SearchPhotosHandler.handleRequest(SearchPhotosHandler.kt:55)
at com.budilov.SearchPhotosHandler.handleRequest(SearchPhotosHandler.kt:27)`

**Comment by vbudilov** [comment]
Let me test this out...

**Comment by vbudilov** [comment]
Fixed.
